### PR TITLE
Fix trading feature not loading

### LINKED ISSUE #197: Trade feature are very unreliable.
It requires a page reload to work.

### PR DESCRIPTION
**Pull request by Sashank999**
Closes #197 .

### CODE REVIEW

File: extension/scripts/features/tradevalues/ttTradeValues.js [hunk 1]
```diff
@@ -13,13 +13,17 @@
...
 	);
 
 	function initialiseListeners() {
+		window.addEventListener("hashchange", () => {
+			const step = getHashParameters().get("step");
+			if (step !== "view" && step !== "initiateTrade" && step !== "accept" && step !== "start") return;
+			if (feature.enabled()) addItemValues();
+		});
 		addXHRListener(({ detail: { page, xhr, json } }) => {
+			xhr.responseURL
```
Comment (DeKleineKobini) [inline extension/scripts/features/tradevalues/ttTradeValues.js:26]: What purpose does this have?
